global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: todoservice
    static_configs:
      - targets: ['172.24.232.13:2222'] # IP where todoservice is exposing its ports
